import type { Locale } from "./i18n";

export type QuizQuestion = {
  text: string;
  answer: boolean;
  explanation: string;
};

type QuestionPair = {
  answer: boolean;
  en: [string, string];
  ja: [string, string];
};

const localize = (questions: QuestionPair[], locale: Locale): QuizQuestion[] =>
  questions.map((question) => {
    const [text, explanation] = question[locale];
    return { text, explanation, answer: question.answer };
  });

const topicQuizPairs: Record<string, QuestionPair[]> = {
  "mantle-basics": [
    { answer: true, en: ["Mantle is an Ethereum Layer 2 ecosystem.", "Mantle is built around scalable on-chain activity."], ja: ["MantleはEthereumのLayer 2エコシステムである。", "Mantleはスケーラブルなオンチェーン活動を支えるエコシステムです。"] },
    { answer: true, en: ["MNT is used in Mantle's network economy.", "MNT is connected to gas, governance, and ecosystem incentives."], ja: ["MNTはMantleのネットワーク経済と関係がある。", "MNTはガス、ガバナンス、エコシステム施策と関係します。"] },
    { answer: true, en: ["Mantle analysis should include apps, liquidity, and users.", "The ecosystem is more than price alone."], ja: ["Mantle分析ではアプリ、流動性、ユーザーを見るとよい。", "Mantleは価格だけでなく、利用状況も見る必要があります。"] },
    { answer: true, en: ["Bridge activity can be a clue for ecosystem demand.", "Moving assets into a network can show attention or usage."], ja: ["ブリッジ活動はエコシステム需要の手がかりになる。", "資産がネットワークに入る動きは注目や利用の材料になります。"] },
    { answer: true, en: ["A healthy Mantle report compares multiple signals.", "Price, liquidity, activity, and wallets are stronger together."], ja: ["良いMantleレポートは複数シグナルを比べる。", "価格、流動性、活動量、ウォレットを合わせると読みやすくなります。"] },
    { answer: true, en: ["Mantle can host DeFi and consumer-facing apps.", "Ecosystem analysis should look at actual app usage."], ja: ["MantleではDeFiやユーザー向けアプリも重要になる。", "エコシステム分析では実際のアプリ利用を見るとよいです。"] },
    { answer: true, en: ["Returning users are useful for judging Mantle activity.", "Repeat usage can show stronger demand than a one-time spike."], ja: ["継続ユーザーはMantle活動を読む材料になる。", "一度だけの急増より、繰り返し利用の方が需要を示しやすいです。"] },
    { answer: true, en: ["Mantle analysis should avoid overclaiming from one clue.", "One clue should guide the next check, not finish the report."], ja: ["Mantle分析では1つの手がかりだけで言い切らない。", "1つの手がかりは次に見る場所を決める材料です。"] },
    { answer: true, en: ["Network fees and speed affect user experience.", "Cheaper and smoother usage can help apps grow."], ja: ["手数料や速度はユーザー体験に影響する。", "安くスムーズに使えることはアプリ成長の助けになります。"] },
    { answer: true, en: ["Mantle ecosystem health can change over time.", "Daily checks make trend changes easier to notice."], ja: ["Mantleエコシステムの健康度は時間とともに変わる。", "毎日見るとトレンドの変化に気づきやすくなります。"] },
    { answer: false, en: ["Mantle is only a profile picture project.", "Mantle is a broader on-chain ecosystem."], ja: ["Mantleはプロフィール画像だけのプロジェクトである。", "Mantleはより広いオンチェーンエコシステムです。"] },
    { answer: false, en: ["MNT price alone explains the whole network.", "Price needs activity, liquidity, and wallet context."], ja: ["MNT価格だけでネットワーク全体が分かる。", "価格には活動量、流動性、ウォレット文脈が必要です。"] },
    { answer: false, en: ["Every bridge deposit is automatically bullish.", "Bridge flow needs size, direction, and follow-through."], ja: ["ブリッジ入金はすべて自動的に強気である。", "規模、方向、その後の利用を見る必要があります。"] },
    { answer: false, en: ["Mantle has no reason to care about app usage.", "App usage is central to ecosystem health."], ja: ["Mantle分析でアプリ利用は気にしなくてよい。", "アプリ利用はエコシステム健康度の中心です。"] },
    { answer: false, en: ["One transaction proves real ecosystem adoption.", "Adoption needs repeated usage and broader context."], ja: ["1件の取引だけで実需が証明される。", "実需には継続利用と広い文脈が必要です。"] },
    { answer: false, en: ["Mantle analysis should ignore liquidity.", "Liquidity affects usability and risk."], ja: ["Mantle分析では流動性を無視してよい。", "流動性は使いやすさとリスクに関係します。"] },
    { answer: false, en: ["All Mantle apps should be judged the same way.", "Different categories need different signals."], ja: ["Mantle上のアプリはすべて同じ基準で見ればよい。", "カテゴリごとに見るべきシグナルは変わります。"] },
    { answer: false, en: ["A good Mantle report should only be hype.", "Useful reports include risk and next checks."], ja: ["良いMantleレポートは盛り上げだけでよい。", "役立つレポートにはリスクと次の確認が必要です。"] },
    { answer: false, en: ["If activity falls, there is nothing to learn.", "Weakness can show risk, rotation, or timing clues."], ja: ["活動量が落ちたら学べることはない。", "弱さからリスク、資金移動、タイミングの手がかりが見えます。"] },
    { answer: false, en: ["Mantle ecosystem discovery is just listing random names.", "Good discovery explains why a project may matter."], ja: ["Mantleの発見は名前をランダムに並べるだけでよい。", "良い発見は、なぜ注目するのかまで説明します。"] },
  ],
  meth: [
    { answer: true, en: ["mETH is related to liquid staking.", "It lets users keep exposure while looking for yield utility."], ja: ["mETHはリキッドステーキングと関係がある。", "ETH系の価値を保ちながら利回りや利用先を探す文脈があります。"] },
    { answer: true, en: ["mETH analysis should ask where yield comes from.", "Yield source is important for risk checks."], ja: ["mETH分析では利回りの源泉を見るべき。", "利回りがどこから来るかはリスク確認に重要です。"] },
    { answer: true, en: ["mETH liquidity affects whether it is easy to use.", "Thin liquidity can make entry and exit harder."], ja: ["mETHの流動性は使いやすさに影響する。", "流動性が薄いと出入りが難しくなります。"] },
    { answer: true, en: ["mETH can be compared with ETH to check market behavior.", "The relationship with ETH helps reveal demand or stress."], ja: ["mETHはETHと比べると市場の状態を見やすい。", "ETHとの関係から需要やストレスが見えることがあります。"] },
    { answer: true, en: ["mETH opportunities can involve DeFi utility.", "Use in lending, liquidity, or strategies can matter."], ja: ["mETHの機会にはDeFiでの使い道も関係する。", "レンディング、流動性、運用戦略で使えるかが重要です。"] },
    { answer: true, en: ["Redemption and withdrawal paths matter for mETH.", "Users need to understand how exits work."], ja: ["mETHでは償還や出金の道筋が重要。", "出口の仕組みを理解する必要があります。"] },
    { answer: true, en: ["mETH demand can be supported by both yield and utility.", "Yield alone is not the only reason to hold it."], ja: ["mETH需要は利回りと実用性の両方で支えられることがある。", "持つ理由は利回りだけとは限りません。"] },
    { answer: true, en: ["Incentives can change mETH usage numbers.", "Rewards can boost activity temporarily."], ja: ["インセンティブはmETH利用数を変化させる。", "報酬で一時的に活動が増えることがあります。"] },
    { answer: true, en: ["mETH risk checks should include liquidity, peg, and yield source.", "These are core parts of a useful mETH read."], ja: ["mETHのリスク確認では流動性、価格差、利回り源泉を見る。", "この3つはmETHを読む基本材料です。"] },
    { answer: true, en: ["mETH can be part of Mantle ecosystem growth.", "If it is used in apps, it can support broader activity."], ja: ["mETHはMantleエコシステム成長の一部になり得る。", "アプリで使われるほど広い活動につながります。"] },
    { answer: false, en: ["mETH is only a meme token.", "mETH is tied to liquid staking, not just meme culture."], ja: ["mETHはただのミームトークンである。", "mETHはリキッドステーキング文脈の資産です。"] },
    { answer: false, en: ["mETH yield is always risk-free.", "Yield always needs source and risk checks."], ja: ["mETHの利回りは常にノーリスクである。", "利回りには必ず源泉とリスク確認が必要です。"] },
    { answer: false, en: ["Liquidity does not matter for mETH.", "Liquidity affects swaps, exits, and risk."], ja: ["mETHでは流動性は関係ない。", "流動性は交換、出口、リスクに影響します。"] },
    { answer: false, en: ["mETH should never be compared with ETH.", "ETH comparison helps read premium, discount, or stress."], ja: ["mETHはETHと比較してはいけない。", "ETH比較でプレミアム、ディスカウント、ストレスを読めます。"] },
    { answer: false, en: ["High APY always means a good mETH opportunity.", "High APY can also mean higher risk or temporary incentives."], ja: ["高APYなら必ず良いmETH機会である。", "高APYは高リスクや一時報酬の可能性もあります。"] },
    { answer: false, en: ["mETH has no connection to Mantle analysis.", "mETH is an important Mantle ecosystem topic."], ja: ["mETHはMantle分析と関係がない。", "mETHはMantleエコシステムの重要テーマです。"] },
    { answer: false, en: ["Redemption paths are unnecessary for mETH research.", "Exit mechanics are part of risk analysis."], ja: ["mETH調査で償還方法は不要である。", "出口の仕組みはリスク分析の一部です。"] },
    { answer: false, en: ["One holder proves mETH adoption.", "Adoption needs broader and repeated usage."], ja: ["1人の保有者だけでmETH普及が証明される。", "普及には広く継続的な利用が必要です。"] },
    { answer: false, en: ["mETH reports should ignore DeFi utility.", "DeFi use can be a major reason mETH matters."], ja: ["mETHレポートではDeFi利用を無視してよい。", "DeFiで使えることはmETHの重要な価値になり得ます。"] },
    { answer: false, en: ["mETH price alone is enough for analysis.", "Price needs liquidity, yield, and usage context."], ja: ["mETH価格だけで分析は十分である。", "価格には流動性、利回り、利用状況の文脈が必要です。"] },
  ],
  rwa: [
    { answer: true, en: ["RWA connects real-world assets with on-chain systems.", "RWA means assets like credit, treasuries, or other real-world value represented on-chain."], ja: ["RWAは現実世界の資産とオンチェーンを結びつける。", "国債、信用、実物価値などをオンチェーンで扱う文脈です。"] },
    { answer: true, en: ["Issuer credibility matters in RWA analysis.", "The party behind the asset affects trust."], ja: ["RWA分析では発行体の信頼性が重要。", "誰が資産を発行・管理しているかは信頼に直結します。"] },
    { answer: true, en: ["RWA liquidity matters.", "A useful asset needs a realistic way to enter or exit."], ja: ["RWAでは流動性が重要になる。", "使える資産には現実的な出入りの道が必要です。"] },
    { answer: true, en: ["RWA yield should be checked for its source.", "Yield from real-world assets needs explanation."], ja: ["RWAの利回りは源泉を確認するべき。", "現実資産由来の利回りは説明が必要です。"] },
    { answer: true, en: ["Custody and legal structure can affect RWA risk.", "Off-chain structure matters even when the asset is on-chain."], ja: ["保管や法的構造はRWAリスクに影響する。", "オンチェーン化されていてもオフチェーン構造は重要です。"] },
    { answer: true, en: ["RWA can become stronger if it is usable in DeFi.", "Composability can turn an asset into practical liquidity."], ja: ["RWAはDeFiで使えると強くなることがある。", "組み合わせて使えると実用性が増します。"] },
    { answer: true, en: ["Redemption paths are important for RWA.", "Users need to know how value returns to them."], ja: ["RWAでは償還の道筋が重要。", "価値をどう戻せるかを確認する必要があります。"] },
    { answer: true, en: ["RWA analysis should separate narrative from demand.", "A popular story is not the same as real usage."], ja: ["RWA分析では話題性と需要を分けて見る。", "人気の物語と実際の需要は別です。"] },
    { answer: true, en: ["Collateral transparency helps RWA trust.", "Clear backing makes the asset easier to evaluate."], ja: ["担保の透明性はRWAの信頼に役立つ。", "裏付けが見えるほど評価しやすくなります。"] },
    { answer: true, en: ["RWA reports should include both opportunity and risk.", "Real-world assets can create yield but also introduce off-chain risk."], ja: ["RWAレポートは機会とリスクの両方を書くべき。", "現実資産は利回りを生む一方、オフチェーンリスクもあります。"] },
    { answer: false, en: ["RWA only needs a strong narrative.", "Narrative is not enough without structure and demand."], ja: ["RWAは強い話題性だけあればよい。", "構造と需要がなければ十分ではありません。"] },
    { answer: false, en: ["Issuer credibility is irrelevant for RWA.", "The issuer is one of the first things to check."], ja: ["RWAでは発行体の信頼性は関係ない。", "発行体は最初に見るべきポイントです。"] },
    { answer: false, en: ["RWA liquidity can be ignored.", "Liquidity changes usability and exit risk."], ja: ["RWAの流動性は無視してよい。", "流動性は使いやすさと出口リスクに影響します。"] },
    { answer: false, en: ["RWA yield appears automatically.", "Yield needs a real source and explanation."], ja: ["RWAの利回りは自動的に生まれる。", "利回りには実際の源泉と説明が必要です。"] },
    { answer: false, en: ["On-chain RWA has no off-chain risk.", "Real-world assets still depend on off-chain legal and custody systems."], ja: ["オンチェーンRWAにはオフチェーンリスクがない。", "現実資産は法務や保管などオフチェーン要素に依存します。"] },
    { answer: false, en: ["All RWA assets should be treated the same.", "Different assets have different risk and liquidity profiles."], ja: ["すべてのRWA資産は同じように扱えばよい。", "資産ごとにリスクや流動性は違います。"] },
    { answer: false, en: ["Redemption does not matter for RWA.", "How users exit is central to the asset's quality."], ja: ["RWAでは償還は重要ではない。", "出口の仕組みは資産の質に直結します。"] },
    { answer: false, en: ["RWA cannot interact with DeFi.", "Some RWA designs can be used in DeFi strategies."], ja: ["RWAはDeFiと相互作用できない。", "設計によってはDeFi戦略で使えます。"] },
    { answer: false, en: ["Price alone proves RWA quality.", "Quality needs issuer, backing, liquidity, and usage checks."], ja: ["価格だけでRWAの質は証明される。", "発行体、裏付け、流動性、利用状況が必要です。"] },
    { answer: false, en: ["RWA has only upside.", "RWA can have credit, custody, legal, and liquidity risks."], ja: ["RWAには上昇余地しかない。", "信用、保管、法務、流動性リスクがあります。"] },
  ],
  "mantle-ecosystem": [
    { answer: true, en: ["Ecosystem discovery looks for useful apps, not just names.", "A good find explains why the app matters."], ja: ["エコシステム発見は名前だけでなく使えるアプリを探す。", "良い発見は、なぜ重要かまで説明します。"] },
    { answer: true, en: ["Returning users can show app stickiness.", "Repeat usage suggests people have a reason to come back."], ja: ["継続ユーザーはアプリの定着度を示す。", "戻ってくる理由がある可能性を示します。"] },
    { answer: true, en: ["Volume spikes need context.", "Spikes may be real demand, incentives, or noise."], ja: ["出来高の急増には文脈が必要。", "実需、インセンティブ、ノイズのどれかを確認します。"] },
    { answer: true, en: ["Comparing categories helps Mantle discovery.", "DeFi, gaming, RWA, and wallets may need different signals."], ja: ["カテゴリ比較はMantle発見に役立つ。", "DeFi、ゲーム、RWA、ウォレットでは見る指標が変わります。"] },
    { answer: true, en: ["Incentives can temporarily boost ecosystem activity.", "Rewards can attract users who may not stay."], ja: ["インセンティブは一時的に活動を増やす。", "報酬目的のユーザーは残らないことがあります。"] },
    { answer: true, en: ["TVL plus activity is stronger than TVL alone.", "Capital and usage together are a better clue."], ja: ["TVLだけよりTVLと活動量の組み合わせが強い。", "資金と利用が一緒にある方が良い手がかりです。"] },
    { answer: true, en: ["Developer activity can support ecosystem confidence.", "Active building can lead to better apps."], ja: ["開発活動はエコシステム信頼の材料になる。", "開発が続くほど良いアプリにつながる可能性があります。"] },
    { answer: true, en: ["Bridge flows can support ecosystem discovery.", "Incoming assets can show where users may act next."], ja: ["ブリッジフローはエコシステム発見に使える。", "入ってきた資産は次に使われる場所のヒントになります。"] },
    { answer: true, en: ["Category diversity can make an ecosystem more resilient.", "Multiple use cases reduce dependence on one theme."], ja: ["カテゴリの多様性はエコシステムを強くする。", "複数用途があると1テーマ依存を減らせます。"] },
    { answer: true, en: ["Good discovery should end with a next check.", "The user should know what to inspect after the report."], ja: ["良い発見は次に見る項目で終わるとよい。", "レポート後に何を確認するか分かるべきです。"] },
    { answer: false, en: ["One spike proves an app has product-market fit.", "A spike needs retention and usage confirmation."], ja: ["一度の急増だけでアプリの成功が証明される。", "定着と利用の確認が必要です。"] },
    { answer: false, en: ["All Mantle projects are equally important.", "Importance depends on usage, liquidity, category, and growth."], ja: ["Mantleの全プロジェクトは同じ重要度である。", "利用、流動性、カテゴリ、成長で重要度は変わります。"] },
    { answer: false, en: ["User retention is irrelevant.", "Retention helps separate real demand from temporary noise."], ja: ["ユーザー定着は関係ない。", "定着は実需と一時ノイズを分ける助けになります。"] },
    { answer: false, en: ["Incentives never affect activity.", "Rewards often change short-term behavior."], ja: ["インセンティブは活動量に影響しない。", "報酬は短期行動を変えやすいです。"] },
    { answer: false, en: ["TVL always means organic demand.", "Some TVL can be incentive-driven or temporary."], ja: ["TVLは常に自然な需要を意味する。", "一部のTVLは報酬目的や一時的な可能性があります。"] },
    { answer: false, en: ["Discovery should ignore app categories.", "Categories explain what signals matter."], ja: ["発見ではアプリカテゴリを無視してよい。", "カテゴリによって重要なシグナルが変わります。"] },
    { answer: false, en: ["Only token price matters for ecosystem discovery.", "Apps, users, liquidity, and retention matter too."], ja: ["エコシステム発見ではトークン価格だけ見ればよい。", "アプリ、ユーザー、流動性、定着も重要です。"] },
    { answer: false, en: ["Inactive apps are always healthy if the website looks good.", "Real usage matters more than appearance."], ja: ["見た目が良ければ非アクティブなアプリも健全である。", "見た目より実利用が重要です。"] },
    { answer: false, en: ["All volume is organic.", "Volume can come from incentives, bots, or short-term campaigns."], ja: ["すべての出来高は自然発生である。", "報酬、ボット、短期キャンペーンの可能性があります。"] },
    { answer: false, en: ["A discovery report does not need a reason.", "Without a reason, the user cannot judge the signal."], ja: ["発見レポートに理由はいらない。", "理由がないとユーザーが判断できません。"] },
  ],
  nansen: [
    { answer: true, en: ["Nansen-style labels are clues, not final truth.", "Labels help organize wallets but still need context."], ja: ["Nansen系ラベルは手がかりであり、最終的な真実ではない。", "ラベルはウォレット整理に役立ちますが文脈が必要です。"] },
    { answer: true, en: ["Wallet behavior can become research material.", "Patterns can reveal attention, confidence, or risk."], ja: ["ウォレット行動はリサーチ素材になる。", "パターンから注目、確信、リスクが見えることがあります。"] },
    { answer: true, en: ["Smart Money signals need confirmation.", "Other signals should support the wallet clue."], ja: ["Smart Moneyシグナルには裏取りが必要。", "ウォレットの手がかりは別シグナルで支えるべきです。"] },
    { answer: true, en: ["Flow direction matters in Nansen analysis.", "Inflow and outflow can mean different things."], ja: ["Nansen分析ではフローの方向が重要。", "流入と流出では意味が変わります。"] },
    { answer: true, en: ["Signal size matters.", "A tiny value should not be treated like a major move."], ja: ["シグナルの規模は重要。", "小さすぎる値を大きな動きのように扱うべきではありません。"] },
    { answer: true, en: ["Timeframe changes the meaning of a signal.", "Daily and weekly behavior can tell different stories."], ja: ["期間によってシグナルの意味は変わる。", "日次と週次では見えるものが変わります。"] },
    { answer: true, en: ["Repeated wallet patterns are stronger than one event.", "Repeat behavior reduces the chance of pure noise."], ja: ["繰り返しのウォレットパターンは1回の動きより強い。", "繰り返しはノイズの可能性を下げます。"] },
    { answer: true, en: ["Nansen data should be summarized for users.", "Raw data needs translation into readable insight."], ja: ["Nansenデータはユーザー向けに要約すべき。", "生データは読みやすい洞察に変換する必要があります。"] },
    { answer: true, en: ["Nansen signals can support Mantle research if they are Mantle-related.", "The cat should reward Mantle-focused analysis most."], ja: ["NansenシグナルはMantle関連ならリサーチに役立つ。", "猫はMantleに関係する分析を高く評価すべきです。"] },
    { answer: true, en: ["A weak Nansen clue can become a watchlist item.", "It may matter later if confirmed by other data."], ja: ["弱いNansen手がかりもウォッチリスト候補になる。", "後で別データで確認できれば価値が出ます。"] },
    { answer: false, en: ["Nansen labels are always perfect.", "Labels are helpful but imperfect."], ja: ["Nansenラベルは常に完璧である。", "ラベルは便利ですが完璧ではありません。"] },
    { answer: false, en: ["One Smart Money wallet is enough for a final conclusion.", "One wallet is only a clue."], ja: ["Smart Moneyウォレット1つで最終判断してよい。", "1つのウォレットは手がかりにすぎません。"] },
    { answer: false, en: ["Raw API data should be shown without explanation.", "Users need a short readable interpretation."], ja: ["APIの生データは説明なしで出すべき。", "ユーザーには短く読みやすい解釈が必要です。"] },
    { answer: false, en: ["Flow size does not matter.", "Size helps judge whether the signal is meaningful."], ja: ["フローの規模は関係ない。", "規模はシグナルの重要度判断に必要です。"] },
    { answer: false, en: ["All wallet movements are bullish.", "Some movement can signal selling, risk, or uncertainty."], ja: ["すべてのウォレット移動は強気である。", "売り、リスク、不確実性を示すこともあります。"] },
    { answer: false, en: ["A zero flow is strong alpha.", "Zero flow is usually weak or empty evidence."], ja: ["フロー0は強いAlphaである。", "0は通常、弱いまたは空の証拠です。"] },
    { answer: false, en: ["Nansen replaces analyst judgment.", "It supports judgment but does not replace it."], ja: ["Nansenは分析判断そのものを置き換える。", "判断を支援しますが、置き換えるものではありません。"] },
    { answer: false, en: ["Context is unnecessary for wallet labels.", "Context is what makes labels useful."], ja: ["ウォレットラベルに文脈は不要である。", "文脈があるからラベルが役立ちます。"] },
    { answer: false, en: ["Every token mention from Nansen is important.", "Mentions need value, size, and follow-through."], ja: ["Nansenに出たトークン名はすべて重要である。", "価値、規模、その後の動きが必要です。"] },
    { answer: false, en: ["Nansen signals should never be compared with price.", "Price comparison can confirm or weaken a signal."], ja: ["Nansenシグナルは価格と比較してはいけない。", "価格比較はシグナルの強弱確認に役立ちます。"] },
  ],
  tvl: [
    { answer: true, en: ["TVL means total value locked.", "It estimates value deposited in protocols."], ja: ["TVLはTotal Value Lockedの略である。", "プロトコルに預けられた価値の目安です。"] },
    { answer: true, en: ["TVL can hint at liquidity and confidence.", "More locked value can show capital attention."], ja: ["TVLは流動性や信頼の手がかりになる。", "預けられた資金は注目や信頼の材料になります。"] },
    { answer: true, en: ["TVL should be compared with activity.", "Capital without usage can be weaker."], ja: ["TVLは活動量と比べて見るべき。", "資金だけで利用がない場合は弱い可能性があります。"] },
    { answer: true, en: ["Incentives can inflate TVL.", "Rewards can attract temporary deposits."], ja: ["インセンティブはTVLを膨らませることがある。", "報酬目的の一時的な預け入れがあります。"] },
    { answer: true, en: ["Rising TVL plus rising users is stronger than TVL alone.", "Multiple signals improve confidence."], ja: ["TVL増加とユーザー増加がそろうと強い。", "複数シグナルがそろうと信頼度が上がります。"] },
    { answer: true, en: ["TVL composition matters.", "Stablecoins, ETH, and volatile assets have different meanings."], ja: ["TVLの中身は重要である。", "ステーブル、ETH、変動資産では意味が変わります。"] },
    { answer: true, en: ["Sudden TVL withdrawals can be a risk signal.", "Capital leaving may show stress or rotation."], ja: ["TVLの急な流出はリスクシグナルになる。", "資金離脱はストレスや資金移動を示すことがあります。"] },
    { answer: true, en: ["TVL should be compared across protocols.", "Comparison reveals relative strength."], ja: ["TVLはプロトコル間で比較するとよい。", "比較により相対的な強さが見えます。"] },
    { answer: true, en: ["Stable TVL can suggest stickiness.", "Capital staying through volatility can be useful."], ja: ["安定したTVLは定着度の手がかりになる。", "変動時にも残る資金は参考になります。"] },
    { answer: true, en: ["Bridge flows can affect chain-level TVL.", "Assets entering a chain can raise locked value later."], ja: ["ブリッジフローはチェーン全体のTVLに影響する。", "資産が入ると後でTVL増加につながることがあります。"] },
    { answer: false, en: ["TVL is always bullish.", "The reason behind TVL matters."], ja: ["TVL増加は常に強気である。", "TVLが増えた理由が重要です。"] },
    { answer: false, en: ["TVL is the same as revenue.", "TVL is deposited value, not protocol revenue."], ja: ["TVLは収益と同じ意味である。", "TVLは預けられた価値で、収益ではありません。"] },
    { answer: false, en: ["Activity does not matter if TVL is high.", "High TVL without usage may be weak."], ja: ["TVLが高ければ活動量は関係ない。", "利用がない高TVLは弱い可能性があります。"] },
    { answer: false, en: ["Incentives never affect TVL.", "Rewards can strongly affect deposits."], ja: ["インセンティブはTVLに影響しない。", "報酬は預け入れに大きく影響します。"] },
    { answer: false, en: ["One-day TVL spikes prove lasting demand.", "Lasting demand needs persistence."], ja: ["1日のTVL急増で長期需要が証明される。", "長期需要には継続が必要です。"] },
    { answer: false, en: ["All TVL is sticky.", "Some deposits leave when rewards end."], ja: ["すべてのTVLは定着資金である。", "報酬終了で抜ける資金もあります。"] },
    { answer: false, en: ["Falling TVL is always fatal.", "It can be risk, rotation, or temporary adjustment."], ja: ["TVL低下は常に致命的である。", "リスク、資金移動、一時調整の可能性があります。"] },
    { answer: false, en: ["TVL proves decentralization.", "TVL does not directly prove decentralization."], ja: ["TVLは分散性を証明する。", "TVLだけでは分散性は証明できません。"] },
    { answer: false, en: ["TVL never needs comparison.", "Comparison makes TVL more meaningful."], ja: ["TVLは比較しなくてよい。", "比較することで意味が強くなります。"] },
    { answer: false, en: ["TVL has no risk information.", "TVL changes can show risk or confidence."], ja: ["TVLにはリスク情報がまったくない。", "TVL変化からリスクや信頼の手がかりが見えます。"] },
  ],
  "whale-tracking": [
    { answer: true, en: ["Whale tracking studies large wallet behavior.", "Large wallets can influence market conditions."], ja: ["大口追跡は大きなウォレットの行動を見る。", "大口ウォレットは市場環境に影響することがあります。"] },
    { answer: true, en: ["Direction matters in whale tracking.", "Buying, selling, depositing, and withdrawing mean different things."], ja: ["大口追跡では方向が重要。", "買い、売り、入金、出金で意味が変わります。"] },
    { answer: true, en: ["Exchange inflow can be a selling risk clue.", "Funds moving to exchanges may become sell pressure."], ja: ["取引所への流入は売りリスクの手がかりになる。", "取引所に向かう資金は売り圧になる可能性があります。"] },
    { answer: true, en: ["Exchange outflow can suggest holding or DeFi use.", "Leaving exchanges may reduce immediate sell pressure."], ja: ["取引所からの流出は保有やDeFi利用の手がかりになる。", "取引所から出ると短期売り圧が減る可能性があります。"] },
    { answer: true, en: ["Repeated whale behavior is stronger than one move.", "Patterns matter more than isolated transactions."], ja: ["繰り返しの大口行動は1回の動きより強い。", "単発取引よりパターンが重要です。"] },
    { answer: true, en: ["Whale signals need liquidity context.", "A large move matters more in thin markets."], ja: ["大口シグナルには流動性の文脈が必要。", "薄い市場では大口の影響が大きくなります。"] },
    { answer: true, en: ["Whale activity can signal both opportunity and risk.", "Accumulation and exit preparation can both appear."], ja: ["大口活動はチャンスにもリスクにもなる。", "蓄積と離脱準備の両方があり得ます。"] },
    { answer: true, en: ["Multiple whales acting similarly can strengthen a signal.", "Clustered behavior is harder to ignore."], ja: ["複数の大口が同じ動きをするとシグナルが強くなる。", "集団的な行動は無視しにくいです。"] },
    { answer: true, en: ["Not every whale is smart money.", "Large size does not always mean good judgment."], ja: ["すべての大口がSmart Moneyとは限らない。", "資金量が大きくても判断が正しいとは限りません。"] },
    { answer: true, en: ["Whale tracking should end with a confirmation step.", "A report should say what signal to check next."], ja: ["大口追跡は確認ステップまで示すとよい。", "次に見るシグナルを示すと役立ちます。"] },
    { answer: false, en: ["Every whale buy is automatically good.", "Whale buys still need context."], ja: ["大口の買いはすべて自動的に良い。", "大口買いにも文脈が必要です。"] },
    { answer: false, en: ["One large wallet gives a final answer.", "One wallet is only one clue."], ja: ["1つの大口ウォレットで最終判断できる。", "1つのウォレットは手がかりの1つです。"] },
    { answer: false, en: ["Whale moves are always bullish.", "Some moves can signal exit risk."], ja: ["大口の動きは常に強気である。", "離脱リスクを示す動きもあります。"] },
    { answer: false, en: ["Exchange inflow always means accumulation.", "Exchange inflow can also mean selling preparation."], ja: ["取引所流入は常に蓄積を意味する。", "売却準備の可能性もあります。"] },
    { answer: false, en: ["Liquidity does not matter for whale tracking.", "Liquidity changes how powerful a whale move is."], ja: ["大口追跡では流動性は関係ない。", "流動性で大口の影響力が変わります。"] },
    { answer: false, en: ["Whales never sell.", "Whales can rotate, sell, or hedge."], ja: ["大口は売らない。", "大口も資金移動、売却、ヘッジをします。"] },
    { answer: false, en: ["Time context is unnecessary.", "Timing can change the meaning of a move."], ja: ["時間軸は必要ない。", "タイミングで動きの意味は変わります。"] },
    { answer: false, en: ["Every large wallet has the same strategy.", "Wallets can have very different goals."], ja: ["すべての大口ウォレットは同じ戦略で動く。", "ウォレットごとに目的は違います。"] },
    { answer: false, en: ["All whale movement is manipulation.", "Some movement is normal allocation or usage."], ja: ["大口の動きはすべて操作である。", "通常の資金配分や利用のこともあります。"] },
    { answer: false, en: ["Whale labels are perfect.", "Labels should be treated as helpful but uncertain."], ja: ["大口ラベルは完璧である。", "ラベルは便利ですが不確実性があります。"] },
  ],
  "wallet-analysis": [
    { answer: true, en: ["Wallet analysis studies behavior over time.", "History helps explain current actions."], ja: ["ウォレット分析は時間をかけた行動を見る。", "履歴は現在の行動を説明する材料になります。"] },
    { answer: true, en: ["Portfolio changes can reveal intent.", "What a wallet adds or removes can be meaningful."], ja: ["ポートフォリオ変化から意図が見えることがある。", "何を増減させたかは意味を持つ場合があります。"] },
    { answer: true, en: ["Transaction frequency can be a clue.", "Active and inactive wallets tell different stories."], ja: ["取引頻度は手がかりになる。", "活発なウォレットと休眠ウォレットでは意味が違います。"] },
    { answer: true, en: ["Counterparties matter in wallet analysis.", "Who a wallet interacts with can reveal strategy."], ja: ["ウォレット分析では相手先が重要。", "どこと取引するかで戦略が見えることがあります。"] },
    { answer: true, en: ["Wallet age gives context.", "New and old wallets should not always be read the same way."], ja: ["ウォレットの年齢は文脈になる。", "新しいウォレットと古いウォレットは同じ読み方とは限りません。"] },
    { answer: true, en: ["Bridge behavior can reveal ecosystem rotation.", "Moving assets across chains can show where attention goes."], ja: ["ブリッジ行動はエコシステム間の資金移動を示す。", "チェーンをまたぐ資金移動は注目先の手がかりです。"] },
    { answer: true, en: ["Gas and activity rhythm can be useful.", "Regular behavior can show real usage."], ja: ["ガス利用や活動リズムは役立つ。", "規則的な行動は実利用の手がかりになります。"] },
    { answer: true, en: ["Wallet cohorts can be compared.", "Groups of similar wallets can reveal a stronger pattern."], ja: ["ウォレットのグループ比較は有効。", "似たウォレット群を見ると強いパターンが見えます。"] },
    { answer: true, en: ["A wallet's holdings can suggest risk appetite.", "Risky or stable holdings tell different stories."], ja: ["保有資産からリスク許容度が見えることがある。", "リスク資産と安定資産では読みが変わります。"] },
    { answer: true, en: ["One transaction is usually not enough.", "Wallet analysis needs repeated behavior."], ja: ["1回の取引だけでは普通は不十分。", "ウォレット分析には繰り返し行動が必要です。"] },
    { answer: false, en: ["Wallet history never matters.", "History is one of the most useful contexts."], ja: ["ウォレット履歴は関係ない。", "履歴はもっとも重要な文脈の1つです。"] },
    { answer: false, en: ["One transaction fully explains a wallet.", "One action rarely tells the full story."], ja: ["1回の取引でウォレット全体が分かる。", "1つの行動だけで全体は分かりにくいです。"] },
    { answer: false, en: ["All wallets behave the same.", "Wallets have different goals and constraints."], ja: ["すべてのウォレットは同じ動きをする。", "目的や制約はウォレットごとに違います。"] },
    { answer: false, en: ["Counterparties are irrelevant.", "Counterparties can reveal exchanges, protocols, or other wallets."], ja: ["取引相手は関係ない。", "取引所、プロトコル、他ウォレットとの関係が見えます。"] },
    { answer: false, en: ["Wallet age is useless.", "Age helps distinguish new experiments from established behavior."], ja: ["ウォレットの年齢は役に立たない。", "新規実験か継続行動かを分ける助けになります。"] },
    { answer: false, en: ["Portfolio changes have no signal.", "Portfolio changes can show rotation or conviction."], ja: ["ポートフォリオ変化はシグナルにならない。", "資金移動や確信度の手がかりになります。"] },
    { answer: false, en: ["Bridge use never matters.", "Bridge use can show cross-chain intent."], ja: ["ブリッジ利用は重要ではない。", "チェーンをまたぐ意図が見えることがあります。"] },
    { answer: false, en: ["Labels are always the final answer.", "Labels need behavior-based confirmation."], ja: ["ラベルは常に最終回答である。", "ラベルは行動で確認する必要があります。"] },
    { answer: false, en: ["Repeated behavior is unnecessary.", "Repeated behavior is what makes wallet analysis stronger."], ja: ["繰り返し行動は必要ない。", "繰り返しこそウォレット分析を強くします。"] },
    { answer: false, en: ["Wallet analysis predicts the future with certainty.", "It gives probabilities and clues, not certainty."], ja: ["ウォレット分析は未来を確実に予測できる。", "確実な予測ではなく、確率と手がかりを出すものです。"] },
  ],
};

export const getQuizQuestions = (topicId: string, locale: Locale): QuizQuestion[] =>
  localize(topicQuizPairs[topicId] ?? topicQuizPairs["mantle-basics"], locale);
